Add prefix to autoscaler_name
epiphany-platform/m-aws-kubernetes-service pull request #20
Opened 2020-10-30 15:05 UTC by rafzei

Add prefix to autoscaler_name
Change reference to private route table by id instead of name & add as input from awsbi

2020-11-02 09:24 UTC, plirglo submitted a review, later dismissed

2020-11-02 16:31 UTC, mkyc requested changes
It would be nice to add some documentation regarding changes.

2020-11-04 09:42 UTC, atsikham commented on resources/defaults.mk
> +M_PRIVATE_ROUTE_TABLE_ID ?= unset
Is there a way to avoid passing this parameter and use `datasource` with custom `filter` or something similar?

2020-11-04 10:45 UTC, rafzei commented on resources/defaults.mk
> +M_PRIVATE_ROUTE_TABLE_ID ?= unset
The second option was to grab it from environment and filter by name but I've talked about it with @sk4zuzu and we agreed we should use it from AwsBI output directly.

2020-11-04 11:42 UTC, mkyc approved these changes
👍

2020-11-04 12:45 UTC, atsikham approved these changes
LGTM

2020-11-04 14:10 UTC, merged