Ability to add EKS to existing subnets
epiphany-platform/m-aws-kubernetes-service pull request #21
Opened 2020-11-03 16:10 UTC by rpudlowski93

PR related to task #18 

- Added ability to run AwsKS cluster in existing subnets.

2020-11-03 16:34 UTC, mkyc requested changes
Two comments. Could you also add table describing parameters similar way as done [here](https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/develop/docs/INPUTS.adoc) in another repo?

2020-11-03 16:34 UTC, mkyc commented on resources/terraform/variables.tf
> +variable "subnets_id" {
description missing

2020-11-03 16:34 UTC, mkyc commented on workdir/Makefile
> -	@yq r $(M_SHARED)/$(M_STATE_FILE_NAME) 'awsbi.output[public_subnet_id.value]' \
it should not be deleted but rather changed into single element list.

2020-11-04 09:56 UTC, rpudlowski93 commented on workdir/Makefile
> -	@yq r $(M_SHARED)/$(M_STATE_FILE_NAME) 'awsbi.output[public_subnet_id.value]' \
I checked the variable - public_subnet_id and we don't use it in our module. I was talking about the var with @atsikham because he added the var to awsbi output and in conclusion it is unnecessary variable and we should remove it, I will comment PR from @rafzei in AwsBI in order to remove it as I mentioned. I can't see any reason why we should hold the variable in this module. We already create EKS only in private subnets and we shouldn't changed it from security reasons.

2020-11-04 10:05 UTC, mkyc commented on workdir/Makefile
> -	@yq r $(M_SHARED)/$(M_STATE_FILE_NAME) 'awsbi.output[public_subnet_id.value]' \
Please talk to @sk4zuzu as well. As far as I remember that was required to have outgoing connection when machines didn't have public IPs, but I'm not sure if I remember correctly.

2020-11-04 10:05 UTC, atsikham requested changes

2020-11-04 10:05 UTC, atsikham commented on resources/defaults.mk
> +M_SUBNETS_ID ?= ["unset"]
Have you checked if `null` can be used here? Like in this [example](https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/03d36c29abae1dfed811f3fc700372e4cce3e314/resources/defaults.mk#L51).

2020-11-04 10:35 UTC, rpudlowski93 commented on resources/terraform/variables.tf
> +variable "subnets_id" {
True, change done

2020-11-04 10:36 UTC, rpudlowski93 commented on resources/terraform/variables.tf
> -variable "autoscaler_name" {
True, thanks, we fixed the same bug two times 👍

2020-11-04 14:10 UTC, rpudlowski93 commented on resources/defaults.mk
> +M_SUBNETS_ID ?= ["unset"]
Approved, I can agree :) Null is better here

2020-11-04 14:16 UTC, rpudlowski93 commented on workdir/Makefile
> -	@yq r $(M_SHARED)/$(M_STATE_FILE_NAME) 'awsbi.output[public_subnet_id.value]' \
I was talking with Michał and I can approve that the var is not necessary and right now is useless. We need just route table from AwsBI

2020-11-04 14:19 UTC, sk4zuzu commented on workdir/Makefile
> -	@yq r $(M_SHARED)/$(M_STATE_FILE_NAME) 'awsbi.output[public_subnet_id.value]' \
I think id of public subnet is not needed for outgoing connections. This could be done in 2 ways. We can use this id and natgw id to create new routing table for new private subnets or we can pass existing routing table and reuse it :) (1 id instead of 2). :thinking:

2020-11-04 14:58 UTC, atsikham commented on CHANGELOG/0.0.2.md
> +* [#18](https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/18) Ability to create EKS in existing subnets.
```suggestion
* [#19](https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/19) - Add prefix to autoscaler_name and private_route_table_id as input variable
* [#18](https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/18) - Ability to create EKS in existing subnets
```

2020-11-04 14:59 UTC, atsikham commented on CHANGELOG/0.0.2.md
> +* [#18](https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/18) Ability to create EKS in existing subnets.
Let's do that the same way as previously - https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/19

2020-11-04 15:02 UTC, atsikham commented on resources/terraform/variables.tf
> +  description = "Existing Subnets id to join to"
```suggestion
  description = "Existing subnet ids to join to"
```

2020-11-04 16:24 UTC, atsikham commented on README.md
> +  * M_SUBNET_IDS = < list of existing subnet ids > (default: null)
```suggestion
Available parameters are listed in the [inputs](docs/INPUTS.adoc) document.
```

2020-11-04 16:25 UTC, atsikham commented on README.md
> +
```suggestion

```

2020-11-04 16:35 UTC, atsikham approved these changes

2020-11-04 18:39 UTC, mkyc submitted a review, later dismissed
LGTM

2020-11-05 07:58 UTC, rafzei commented
Please hold on with merging that. I want to take a look.

2020-11-05 08:50 UTC, rafzei requested changes

2020-11-05 08:50 UTC, rafzei commented on README.md
> +   This commad will create configuration file of AwsKS module in /tmp/shared/awsks/awsks-config.yml. You can investigate what is stored in that file. Available parameters are listed in the [inputs](d
It's a lie. In inputs.adoc AWS keys are marked as "required". Init doesn't need this.

2020-11-05 08:50 UTC, rafzei commented on README.md
> +  Available parameters are listed in the [inputs](docs/INPUTS.adoc) document.
It's a lie. In inputs.adoc AWS keys are marked as "required". Init doesn't need this.

2020-11-05 08:50 UTC, rafzei commented on docs/INPUTS.adoc
> +== Input parameters
This file seems to be a nice reference but only for creating vars.mk file in "examples".
Or we can change "Required" column to "Required in" and specify the commands which require it.

2020-11-05 09:08 UTC, atsikham commented on docs/INPUTS.adoc
> +== Input parameters
@rafzei yes, agree. That file describes needs of the module in general and it's based on `defaults.mk`.

2020-11-05 14:35 UTC, rpudlowski93 commented on docs/INPUTS.adoc
> +== Input parameters
What DYT about last commit? For me it looks readable now. @rafzei @atsikham

2020-11-05 15:05 UTC, atsikham approved these changes

2020-11-05 15:05 UTC, atsikham commented on docs/INPUTS.adoc
> +== Input parameters
For me it's ok :thumbsup:

2020-11-05 15:31 UTC, mkyc approved these changes

2020-11-05 15:31 UTC, mkyc commented on docs/INPUTS.adoc
> +== Input parameters
Yeah, that was good point @rafzei

2020-11-06 07:26 UTC, rafzei approved these changes

2020-11-06 08:17 UTC, merged