Integration tests
epiphany-platform/m-aws-kubernetes-service pull request #29
Opened 2020-12-02 14:50 UTC by seriva

Needs more work:

-,Fix/Add tests
- Proper cleanup
- Integrate properly with new stuff from: #21

2020-12-14 12:25 UTC, atsikham requested changes

2020-12-14 12:25 UTC, atsikham commented on integration_test.go
> +	resourcesTypesToRemove := []string{"Instance", "SecurityGroup", "NatGateway", "EIP", "InternetGateway", "Subnet", "RouteTable", "VPC"}
Probably the order should be changed, https://forums.aws.amazon.com/thread.jspa?threadID=92407

2020-12-14 12:42 UTC, seriva commented on integration_test.go
> +	rgName := moduleName + "-rg"
Yes its correct as the code should remove resources used during testing which includes stuff from basic-infra module. Its similar that module and should be moved to a separate GO library down the road.

2020-12-14 12:44 UTC, seriva commented on integration_test.go
> +	resourcesTypesToRemove := []string{"Instance", "SecurityGroup", "NatGateway", "EIP", "InternetGateway", "Subnet", "RouteTable", "VPC"}
Tried and tested code from basic-infrastructure module which I have no issues with so seems fine.

2020-12-14 13:08 UTC, seriva commented on Makefile
>  		-t $(USER)/$(IMAGE):$(VERSION) \
Fixed

2020-12-14 13:09 UTC, seriva commented on Makefile
> +	@echo "$$AWS_CREDENTIALS_CONTENT" > $(ROOT_DIR)/awscreds.mk
Nope as it contains credentials.

2020-12-14 13:10 UTC, seriva commented on integration_test.go
> +	awsksImageTag = "epiphanyplatform/awsks:0.0.1"
Yeah this needs probably some changes to facilitate running it on the pipeline.

2021-01-05 15:57 UTC, mkyc requested changes
Rather little comments

2021-01-05 15:57 UTC, mkyc commented on Makefile
> +needs-%:
smart

2021-01-05 15:57 UTC, mkyc commented on Makefile
> +metadata: guard-VERSION guard-IMAGE guard-USER
```suggestion
metadata: guard-VERSION guard-IMAGE guard-USER needs-docker
```

2021-01-05 15:57 UTC, mkyc commented on integration_test.go
> +	//"github.com/gruntwork-io/terratest/modules/k8s"
```suggestion
```

2021-01-05 15:57 UTC, mkyc commented on integration_test.go
> +	awsksImageTag = "epiphanyplatform/awsks:0.0.1"
yeah, this should be externalised. Possible way is to use environment variable and setup it [like this](https://github.com/epiphany-platform/cli/blob/develop/pkg/az/az_integration_test.go#L18-L35).

2021-01-05 15:57 UTC, mkyc commented on integration_test.go
> +	awsAccessKey, awsSecretKey := getAwsCreds(t)
```suggestion
func TestApply(t *testing.T) {
	t.Skip() //TODO: Enable when the following issue is fixed: https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/32
	awsAccessKey, awsSecretKey := getAwsCreds(t)
```

2021-01-05 15:57 UTC, mkyc commented on integration_test.go
> +*/
```suggestion
```

2021-01-05 15:57 UTC, mkyc commented on integration_test.go
> +const (
please move const section to head of file

2021-01-07 08:29 UTC, seriva commented on integration_test.go
> +	awsAccessKey, awsSecretKey := getAwsCreds(t)
Good one:)

2021-01-07 08:30 UTC, seriva commented on Makefile
> +needs-%:
thank @sk4zuzu

2021-01-07 13:39 UTC, seriva commented on integration_test.go
> +	awsksImageTag = "epiphanyplatform/awsks:0.0.1"
Made them available externally through env variables.

2021-01-07 15:20 UTC, mkyc approved these changes
LGTM

2021-01-08 07:44 UTC, atsikham approved these changes
LGTM

2021-01-08 07:56 UTC, merged