add few more parameters
epiphany-platform/m-aws-kubernetes-service pull request #30
Opened 2020-12-08 21:51 UTC by ar3ndt

2020-12-09 09:26 UTC, sk4zuzu commented on resources/terraform/modules/nodes/main.tf
> +    ec2_ssh_key  = var.ec2_ssh_key
Doesn't this force users to provide the key while it's not strictly necessary? :thinking:

2020-12-09 09:36 UTC, ar3ndt commented on resources/terraform/modules/nodes/main.tf
> +    ec2_ssh_key  = var.ec2_ssh_key
It doesn't. First I wanted to use count with true/false condition checking if it is set but it applies only for 'resource'. Simply leaving null wont take it into account.

2020-12-10 08:40 UTC, sk4zuzu submitted a review, later dismissed
LGTM

2020-12-10 08:44 UTC, sk4zuzu commented
> LGTM

I think the issue states that we need more parameters:
- worker_groups [instance_type, asg_desired_capacity, asg_min_size, asg_max_size]

What happens with those, do we implement them in another PR? :thinking:

2020-12-10 10:16 UTC, ar3ndt commented
> > LGTM
> 
> I think the issue states that we need more parameters:
> 
> * worker_groups [instance_type, asg_desired_capacity, asg_min_size, asg_max_size]
> 
> What happens with those, do we implement them in another PR? 🤔

True, these parameters are already introdued with defaults but not changeable by user. I will add this

2020-12-10 12:15 UTC, ar3ndt commented
> > > LGTM
> > 
> > 
> > I think the issue states that we need more parameters:
> > 
> > * worker_groups [instance_type, asg_desired_capacity, asg_min_size, asg_max_size]
> > 
> > What happens with those, do we implement them in another PR? thinking
> 
> True, these parameters are already introdued with defaults but not changeable by user. I will add this

updated

2020-12-11 13:11 UTC, atsikham requested changes

2020-12-11 13:11 UTC, atsikham commented on resources/defaults.mk
> +M_DISK_SIZE ?= 36
Why 36?

2020-12-11 13:11 UTC, atsikham commented on resources/defaults.mk
> +M_WORKER_GROUPS_ASG_MAX_SIZE ?= 1
What do you think to combine it in a [similar](https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/develop/resources/defaults.mk#L12) way across modules? [This](https://github.com/epiphany-platform/m-azure-kubernetes-service/pull/28/commits/50304ecb12f2c0ec1d4e57a1f99cd0eb5c7f06e0) change is necessary to do that.

2020-12-11 13:11 UTC, atsikham commented on resources/terraform/main.tf
> +  depends_on                                  = [module.control_plane, module.nodes]
please move this line to the bottom.

2020-12-11 13:11 UTC, atsikham commented on resources/terraform/main.tf
> +  autoscaler_version                          = local.autoscaler_version
We don't need local values that are the same as variables.

2020-12-11 13:11 UTC, atsikham commented on resources/terraform/modules/autoscaler/locals.tf
> +  autoscaler_scale_down_utilization_threshold = var.autoscaler_scale_down_utilization_threshold
We don't need local values that are the same as variables.

2020-12-13 23:11 UTC, ar3ndt commented on resources/defaults.mk
> +M_DISK_SIZE ?= 36
the same as for azure

2020-12-14 09:12 UTC, atsikham requested changes

2020-12-14 09:12 UTC, atsikham commented on resources/defaults.mk
> +M_DISK_SIZE ?= 36
But there is 32 - https://github.com/epiphany-platform/m-azure-basic-infrastructure/blob/887dd68a1f57ae5b22a41564ebbc45ad426fe43c/resources/terraform/modules/vms/main.tf#L78
If there is 36 somewhere, was that done by purpose?

2020-12-14 09:12 UTC, atsikham commented on resources/templates.mk
> +  worker_groups: [$(M_WORKER_GROUPS)]
M_WORKER_GROUPS should be a list of objects. Did you test how specifying a few worker groups works?

2020-12-14 09:12 UTC, atsikham commented on resources/terraform/modules/nodes/main.tf
> +    ec2_ssh_key  = var.ec2_ssh_key
@ar3ndt If you need that behaviour that you mentioned, there is [dynamic blocks](https://www.terraform.io/docs/configuration/expressions/dynamic-blocks.html) for that.
Now nothing should bechanged here.

2020-12-14 09:16 UTC, atsikham commented
Please discuss with @seriva which pr - #29 or #30 will be merged first. I'm not 100% sure, but they may affect each other.

2020-12-14 09:26 UTC, ar3ndt commented on resources/defaults.mk
> +M_DISK_SIZE ?= 36
here it is 36.
https://github.com/epiphany-platform/m-azure-kubernetes-service/blob/develop/resources/defaults.mk

2020-12-14 09:28 UTC, ar3ndt commented
> Please discuss with @seriva which pr - #29 or #30 will be merged first. I'm not 100% sure, but they may affect each other.

I this #29 should go first as it blocks pipeline

2020-12-14 10:54 UTC, atsikham commented on resources/defaults.mk
> +M_DISK_SIZE ?= 36
I suggest to leave default value as 32 as it's something commonfor disk size.

2020-12-14 22:45 UTC, atsikham approved these changes

2020-12-16 12:25 UTC, mkyc commented
@ar3ndt please connect this PR to issue in ZH.

2020-12-23 09:10 UTC, sk4zuzu approved these changes
LGTM

2020-12-23 09:13 UTC, merged