Additional functionality for tests
epiphany-platform/m-aws-kubernetes-service pull request #33
Opened 2020-12-15 01:52 UTC by atsikham

Added additional things such as:
* ENIs detach/remove for safe subnets deletion
* EKS resources deletion (eks, node group, iam, cloudwatch log group)

I'm wasn't able to fix an issue with ENIs, but found such issue that can be related - https://github.com/aws/amazon-vpc-cni-k8s/issues/1223, probably we need a workaround to handle ENIs related to k8s nodes.

2020-12-15 07:16 UTC, seriva commented on integration_test.go
> +                fmt.Println(aerr.Error())
No t.Fatal here?

2020-12-15 07:16 UTC, seriva commented on integration_test.go
> +            switch aerr.Code() {
This is a general comment about all these error handling switch blockes inside this review. Just wondering if the level of handling like thatis needed? Maybe just something like:

```Go
 if aerr, ok := err.(awserr.Error); ok {
    t.Fatal(aerr.Code(), aerr.Error())
   ....
```

2020-12-15 07:16 UTC, seriva commented on resources/terraform/infra.tf
> +    Name                                = "${var.name}-eks-subnet${count.index}"
Any issues with this when its lowercase?

2020-12-15 07:16 UTC, seriva commented on integration_test.go
> +                fmt.Println(aerr.Error())
No t.Fatal here?

2020-12-15 09:53 UTC, atsikham commented on resources/terraform/infra.tf
> +    Name                                = "${var.name}-eks-subnet${count.index}"
Yes, resource name depends on this tag. When lowercase is used, there is no resource name displayed.

2020-12-15 09:56 UTC, atsikham commented on integration_test.go
> +            switch aerr.Code() {
This is how it's done in API usage [examples](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#EKS.DeleteCluster), not for all API there is an example, but in each existing it's so. So final decision is to change that?

2020-12-15 10:45 UTC, atsikham commented on integration_test.go
> +                fmt.Println(aerr.Error())
Fixed.

2020-12-15 10:45 UTC, atsikham commented on integration_test.go
> +                fmt.Println(aerr.Error())
Fixed.

2020-12-15 11:18 UTC, seriva commented on integration_test.go
> +            switch aerr.Code() {
For me it doesnt something like this just doesnt make much sence:

```Go
	    case eks.ErrCodeResourceInUseException:
                t.Fatal(eks.ErrCodeResourceInUseException, aerr.Error())
            case eks.ErrCodeClientException:
                t.Fatal(eks.ErrCodeResourceInUseException, aerr.Error())
            case eks.ErrCodeServerException:
                t.Fatal(eks.ErrCodeResourceInUseException, aerr.Error())
            case eks.ErrCodeServiceUnavailableException:
                t.Fatal(eks.ErrCodeResourceInUseException, aerr.Error())
```
I would at least just put this under default with:

```Go
t.Fatal(aerr.Code(), aerr.Error())
```

2020-12-15 14:59 UTC, erzetpe requested changes

2020-12-15 14:59 UTC, erzetpe commented on integration_test.go
> +					switch aerr.Code() {
This looks weird. why like that?

2020-12-15 14:59 UTC, erzetpe commented on integration_test.go
> +				switch aerr.Code() {
Same here.

2020-12-15 14:59 UTC, erzetpe commented on integration_test.go
> +				switch aerr.Code() {
Maybe easier here will be to use if and switch is an overkill?

2020-12-15 14:59 UTC, erzetpe commented on integration_test.go
> +					switch aerr.Code() {
Same here.

2020-12-15 14:59 UTC, erzetpe commented on integration_test.go
> +				switch aerr.Code() {
Same here.

2020-12-15 14:59 UTC, erzetpe commented on integration_test.go
> +			case cloudwatchlogs.ErrCodeResourceNotFoundException:
Maybe here will be better to use if?

2020-12-15 14:59 UTC, erzetpe commented on integration_test.go
> +			switch aerr.Code() {
Same here.

2020-12-15 14:59 UTC, erzetpe commented on integration_test.go
> +			switch aerr.Code() {
Same here.

2020-12-16 11:18 UTC, erzetpe approved these changes

2020-12-16 12:26 UTC, mkyc commented
@atsikham please connect this PR to issue in ZH.

2020-12-16 12:46 UTC, atsikham commented
@mkyc done

2020-12-17 09:00 UTC, seriva approved these changes

2020-12-29 08:57 UTC, merged