Initial module configuration
epiphany-platform/m-aws-kubernetes-service pull request #4
Opened 2020-09-28 14:25 UTC by atsikham

Not ready yet

2020-10-02 10:01 UTC, mkyc requested changes

2020-10-02 10:32 UTC, atsikham commented on Dockerfile
> +RUN helm repo add stable https://kubernetes-charts.storage.googleapis.com
tried do this and finally was able to fix issues only with current user usage

2020-10-02 10:34 UTC, atsikham commented on resources/defaults.mk
> +M_K8S_AUTOSCALER_VERSION ?= v1.17.3
@mkyc this is a question to discuss. I think so, there is extensive description in this PR.

2020-10-02 10:35 UTC, atsikham commented on resources/terraform/main.tf
> +# Need to create private subnets as it's not done by awsbi module.
@mkyc this is a question to discuss. I think so, there is extensive description in this PR.

2020-10-02 10:41 UTC, atsikham commented on resources/terraform/modules/awsks/versions.tf
> +    }
This is present in [spike](https://github.com/epiphany-platform/epiphany/blob/feature/eks-cluster-creation/docs/design-docs/eks/terraform-scripts/main.tf) and [example](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/main.tf) of module usage and module [documentation](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/README.md#requirements). 
Do we need to check? I wonder if we need to do such things in this PR as it wasn't aim of the task.

2020-10-02 11:06 UTC, atsikham commented on resources/terraform/output.tf
> +output "vpc" {
it was used for debug, removed

2020-10-02 11:27 UTC, mkyc commented on resources/terraform/modules/awsks/versions.tf
> +    }
Ok, so more general question would be if we want to use this eks module at all? Also from this PR description I assume there should be new task about changing it to pure terraform aws provider implementation.

2020-10-02 11:29 UTC, mkyc commented on resources/terraform/main.tf
> +# Need to create private subnets as it's not done by awsbi module.
Yeah, so we should probably create those.

2020-10-02 11:40 UTC, mkyc commented on Dockerfile
> +RUN helm repo add stable https://kubernetes-charts.storage.googleapis.com
Ok, let's not focus on that one for now.

2020-10-02 12:22 UTC, atsikham commented
Created new tasks: #6, #7, and [infrastructure](https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/6) related.

2020-10-02 12:37 UTC, atsikham commented on resources/terraform/modules/awsks/autoscaler.tf
> +resource "helm_release" "cluster-autoscaler" {
Added this to #7

2020-10-02 12:39 UTC, atsikham commented on resources/terraform/modules/awsks/autoscaler-iam.tf
> +    resources = ["*"]
No, I'm not sure. It was done so in the spike and module [examples](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/irsa/irsa.tf). I'll create #8 task soon.

2020-10-02 12:48 UTC, atsikham commented on resources/terraform/modules/awsks/autoscaler-iam.tf
> +    resources = ["*"]
The same as in next comment.

2020-10-02 12:57 UTC, mkyc approved these changes
LGTM

2020-10-06 13:03 UTC, seriva approved these changes

2020-10-06 13:04 UTC, pyrkamarcin approved these changes

2020-10-06 13:06 UTC, merged