Pass module name and AWS region to integration tests
epiphany-platform/m-aws-kubernetes-service pull request #44
Opened 2021-02-03 14:46 UTC by atsikham

These changes allow to pass module name and AWS region to tests to identify which pipeline created resources are related to and in which region.

2021-02-04 13:56 UTC, mkyc requested changes
One general question.

2021-02-04 13:56 UTC, mkyc commented on integration_test.go
> +`, defaultRegion),
is that correct? What if I run tests on different region?

2021-02-04 13:59 UTC, atsikham commented on integration_test.go
> +`, defaultRegion),
Yes, as this "init with defaults" test checks defaults and changing default value will require changing this value in tests.

2021-02-04 17:45 UTC, mkyc commented on integration_test.go
> +`, defaultRegion),
Ah yeah, sorry I didn't notice that you use it in `init` part only.

2021-02-04 17:48 UTC, mkyc approved these changes
LGTM

2021-02-05 09:00 UTC, seriva approved these changes

2021-02-05 09:02 UTC, merged